- name: "Установка Docker и Docker Compose"
  hosts: localhost
  become: true

  tasks:
    - name: "Обновление пакетов"
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        cache_valid_time: 3600

    - name: "Установка необходимых пакетов"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: "Добавить Docker GPG-ключ"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Добавить репозиторий"
      apt_repository: 
        repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
        state: present
        update_cache: yes    

    - name: "Обновить кэш пакетов"
      apt:
        update_cache: yes
      register: apt_cache_updated
      until: apt_cache_updated is succeeded
      retries: 3
      delay: 10

    - name: "Установить Docker CE"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        force_apt_get: yes 

    - name: "Запустить и включить Docker"
      service:
        name: docker
        state: started
        enabled: yes

  
    - name: "Установить Docker Compose"
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    
    - name: "Проверить, что Docker установлен"
      command: docker --version
      register: docker_check
      changed_when: false
      ignore_errors: yes 

    - name: "Проверить, что Docker Compose установлен"
      command: docker-compose --version
      register: compose_check
      changed_when: false
      ignore_errors: yes

    - name: "Отчёт об установке"
      debug:
        msg:
          - "Docker: {{ 'Установлен (' + docker_check.stdout + ')' if docker_check is succeeded else 'Не установлен' }}"
          - "Docker Compose: {{ 'Установлен (' + compose_check.stdout + ')' if compose_check is succeeded else 'Не установлен' }}"