---
- name: "Установка Docker и Docker Compose"
  hosts: localhost
  become: yes  
  tasks:

    - name: "Обновление системы"
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        cache_valid_time: 3600 

    - name: "Установка необходимых пакетов"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: "Добавить Docker GPG-ключ"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Добавить репозиторий Docker"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: "Обновить кэш пакетов"
      apt:
        update_cache: yes

    - name: "Установить Docker CE"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        force_apt_get: yes

    - name: "Запустить и включить Docker"
      service:
        name: docker
        state: started
        enabled: yes

    - name: "Установить Docker Compose"
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'  
      register: download_result
      retries: 3 
      delay: 10  

    - name: "Проверить версию Docker"
      command: docker --version
      register: docker_version
      changed_when: false 

    - name: "Проверить версию Docker Compose"
      command: docker-compose --version
      register: compose_version
      changed_when: false

    - name: "Вывести информацию"
      debug:
        msg:
          - "Docker: {{ docker_version.stdout }}"
          - "Docker Compose: {{ compose_version.stdout }}"
